name: GitHub Page
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: |
          cat <<-EOF > config.json
          {
            "NODE_ENV": "production",
            "USE_ABSOLUTE_ROUTE": true,
            "USE_HTTPS": false,
            "URL": "https://bill42362.github.io/smooth-swpieable",
            "GOOGLE_ANALYTICS_ID": ""
          }
          EOF
      - run: cat config.json
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run buildstatic
      - uses: actions/upload-artifact@v1
        with:
          name: dist-client
          path: dist/client
